apiVersion: apps/v1
kind: Deployment
metadata:
  name: trustyai-operator
  namespace: trustyai-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: trustyai-operator
  template:
    metadata:
      labels:
        control-plane: trustyai-operator
    spec:
      serviceAccountName: controller-manager
      containers:
        - name: trustyai-operator
          image: na.artifactory.swg-devops.com/sys-linux-power-team-ftp3distro-docker-images-docker-local/trustyai-service-operator:latest
          command:
            - /manager
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi